language: python
sudo: false

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"

matrix:
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "nightly"

virtualenv:
  system_site_packages: false

services:
  - postgresql

install:
  - pip install -U pip
  # only eggs: do an erreur with wheel
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7-dev' ]]; then pip install python_editor texttable PyYAML simplejson; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'nightly' ]]; then pip install python_editor texttable PyYAML simplejson; fi
  # only wheel
  - pip install wheel
  - pip install psycopg2
  - pip install anyblok
  - pip install marshmallow --pre
  - pip install passlib
  - pip install flake8
  - pip install coverage
  - pip install nose
  - pip install WebTest
  - pip install coveralls
  - python setup.py develop

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres

script:
  - flake8 anyblok_pyramid_rest_api --ignore F999
  - psql -c 'create database travis_ci_test;' -U postgres
  - nosetests anyblok_pyramid_rest_api/tests -v -s --with-coverage --cover-package=anyblok_pyramid_rest_api
  
after_success:
  coveralls
